### ISSUE TITLE
Apostrophes in prompt mode cause crashes

### ISSUE THREAD

**Issue by inducer** [bram85/topydo#107]
```
topydo> add read matt's draft
Traceback (most recent call last):
  File "/home/andreas/pool/bin/topydo", line 11, in <module>
    sys.exit(main())
  File "/home/andreas/pool/local/lib/python2.7/site-packages/topydo/cli/UILoader.py", line 45, in main
    PromptApplication().run()
  File "/home/andreas/pool/local/lib/python2.7/site-packages/topydo/cli/Prompt.py", line 103, in run
    user_input = shlex.split(user_input)
  File "/home/andreas/pool/local/lib/python2.7/site-packages/ushlex.py", line 298, in split
    else:       return list(lex)
  File "/home/andreas/pool/local/lib/python2.7/site-packages/ushlex.py", line 283, in next
    token = self.get_token()
  File "/home/andreas/pool/local/lib/python2.7/site-packages/ushlex.py", line 99, in get_token
    raw = self.read_token()
  File "/home/andreas/pool/local/lib/python2.7/site-packages/ushlex.py", line 185, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

**Comment by mruwek** [comment]
You have to esape this single-quote or wrap the whole text in double-quotes. I'm afraid we can only provide more friendly error message in such cases, since we're using single and double quotes as delimiters for some long options (like `-F` for example).

**Comment by inducer** [comment]
I'm OK with having to quote stuff as a UI matter, but I think crashing is not that great.
