### ISSUE TITLE
Filtering "t ls \(A\) -- -@wo" only works without a space

### ISSUE THREAD

**Issue by rcraggs** [bram85/topydo#185]
To filter for Priority A tasks without the @wo context works is I do the following with no space between the close bracket and double-hyphen (`t` is my alias for topydo).

`t ls \(A\)-- -@wo`

However if I put a space in, it returns no results

`t ls \(A\)-- -@wo`

The same applies in column view without escaping the brackets

`(A)-- -@wo` works but `(A) -- -@wo` doesn't. 

Not a huge issue because there's the obvious workaround, but it seems like a parser issue?

@ @

**Comment by mruwek** [comment]
I'll look into that, but You can also write it as:

`t ls \(A\) -@wo` or just `ls (A) -@wo` in column ui or prompt mode.

Double minus sign is needed only if you put negated filter before any other positive filter, because first non-option argument stops option processing (as in POSIX spec).

**Comment by mruwek** [comment]
Ok. I think I've investigated it enough. It's simply behavior of `getopt.getopt()` from Python standard library:

(tested via interactive interpreter with python3.6):
```python
>>> from getopt import getopt
>>> getopt(['-x', 'foo', '--', '-bar'], 'xyz')
([('-x', '')], ['foo', '--', '-bar'])
>>> getopt(['-x', 'foo', '-bar'], 'xyz')
([('-x', '')], ['foo', '-bar'])
>>> getopt(['-x', '--', 'foo', '-bar'], 'xyz')
([('-x', '')], ['foo', '-bar'])

```

As we can see in first example `getopt()` didn't remove `--` argument when it was implanted unnecessarily (after already a non-opt argument *foo*). Topydo treats in such situation `--` as an arg for its filters, and since user probably doesn't have todo-items with *--* string the result is empty.

In next example where `--` was totally absent,  we get expected results: *foo* is a non-opt arg so `getopt()` properly treats `-bar` as also a non-opt. In the third example, where `--` was placed [as designed](https://github.com/python/cpython/blob/3.6/Lib/getopt.py#L88) to distinguish `-x` opt and rest of non-opt args, `--` is properly removed from args and *-bar* is treated as a non-opt (as expected).

I can imagine 3 solutions:
1. Do nothing and inform users about proper usage of `--` (according to POSIX spec).
2. Use [`getopt.gnu_getopt()`](https://docs.python.org/3/library/getopt.html#getopt.gnu_getopt) instead of `getopt.getopt()`.
3. Strip `--` from args after `getopt()` has done its job.

Solution #*2* would work with use-case reported above as it allows to mix opt and non-opt args. However results for my examples would be different:

```python
>>> from getopt import gnu_getopt
>>> gnu_getopt(['-x', 'foo', '--', '-bar'], 'xyz')
([('-x', '')], ['foo', '-bar'])
>>> gnu_getopt(['-x', 'foo', '-bar'], 'xyz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/getopt.py", line 138, in gnu_getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "/usr/lib/python3.6/getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "/usr/lib/python3.6/getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -b not recognized
>>> gnu_getopt(['-x', '--', 'foo', '-bar'], 'xyz')
([('-x', '')], ['foo', '-bar'])
```

Since `gnu_getopt()` allows mixing opts and non-opts freely, the first example, resembling the reported one, would work. But the second one (POSIX compliant) would not, because *-bar* is treated here as `-b` option with value *ar*, and since `-b` wasn't declared as a supported opt `gnu_getopt()` throws error in our face. Third example is of course perfectly valid, as expected.

@bram85:
What do you think about this?

**Comment by bram85** [comment]
In general I don't like behavioral changes, so I'd opt for option 1 (pun intended).
