### ISSUE TITLE
Columns on Win10 seems broken?

### ISSUE THREAD

**Issue by russellallen** [bram85/topydo#194]
Installing with `pip3 install topydo[columns]` seemed to work but:

`C:\Users\mail
λ topydo columns
Traceback (most recent call last):
  File "c:\users\mail\scoop\apps\python\3.6.2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mail\scoop\apps\python\3.6.2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mail\scoop\apps\python\current\scripts\topydo.exe\__main__.py", line 9, in <module>
  File "c:\users\mail\scoop\apps\python\3.6.2\lib\site-packages\topydo\ui\UILoader.py", line 51, in main
    UIApplication().run()
  File "c:\users\mail\scoop\apps\python\3.6.2\lib\site-packages\topydo\ui\columns\Main.py", line 176, in __init__
    self._screen = urwid.raw_display.Screen()
  File "c:\users\mail\scoop\apps\python\3.6.2\lib\site-packages\urwid\raw_display.py", line 89, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
`

I think `fcntl` is a Windows only thing.

**Comment by mruwek** [comment]
It's actually urwid's bug: urwid/urwid#152. They're not supporting Windows just yet. If you really want to use the column ui on Windows you have to do that with Cygwin (that's what I'm doing myself).

Sidenote: other topydo modes (cli and prompt) should however work just fine.

**Comment by MinchinWeb** [comment]
@russellallen yes, `fcntl`, near as I can tell, is part of the Python standard library that doesn't exist for Windows.

**Comment by bram85** [comment]
I addressed this in the documentation (yet to be put online).

**Comment by russellallen** [comment]
Thanks, I'll try cygwin. FWIW, cli and prompt do work well.
