### ISSUE TITLE
Proper Unicode support

### ISSUE THREAD

**Issue by mruwek** [bram85/topydo#21]
With undergoing work towards porting topydo to python3 and supporting [jonathanslenders/python-prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) we need to fix all errors with unicode decoding and encoding.

**Comment by mruwek** [comment]
`topydo ical` returns this:
```
Traceback (most recent call last):
  File "/home/jacek/.local/bin/topydo", line 9, in <module>
    load_entry_point('topydo==0.3', 'console_scripts', 'topydo')()
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/cli/UILoader.py", line 39, in main
    CLIApplication().run()
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/cli/CLI.py", line 56, in run
    if self._execute(subcommand, args) == False:
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 200, in _execute
    if command.execute() != False:
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/commands/IcalCommand.py", line 47, in execute
    return super(IcalCommand, self).execute()
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/commands/ListCommand.py", line 67, in execute
    self._print()
  File "/home/jacek/.local/lib/python2.7/site-packages/topydo/commands/IcalCommand.py", line 35, in _print
    self.out(str(self._view()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0107' in position 146: ordinal not in range(128)
```

**Comment by bram85** [comment]
Are you confident we can close this one? Haven't seen Unicode-bugs for a while.

**Comment by mruwek** [comment]
`ls -f ical`, `ls -f json`, `edit`, `append` and `add` all work well. Those are in my opinion the most susceptible commands for possible UnicodeErrors.

 +1 from me to closing this one.
