### ISSUE TITLE
[SOLVED] Lost topydo column mode, following installation, then uninstallation, of terminal_velocity

### ISSUE THREAD

**Issue by RonCam** [bram85/topydo#210]
I am attempting, unsuccessfully, to recover columns mode by reinstalling it.  After (what I think should be) a reinstallation, entering the command _td columns_ in terminal produces, not columns, but the error message copied below. 

The error message was my first indication that something had gone wrong, after my experiment with _terminal_velocity_, and now I'm unable to get back to _topydo_'s previous state.

What _is_ working, are the commands _topydo_, _td_ (the alias), and _td prompt_.  Could someone take a look at the error message that results from the command _td columns_ and give me an idea of where to go?  Columns mode is really great, I do depend upon it, and I'd hate to lose it!

```

:~$ sudo pip3 install topydo[columns] --upgrade --user
Requirement already up-to-date: topydo[columns] in ./.local/lib/python3.4/site-packages
  Installing extra requirements: 'columns'
Cleaning up...
ron@ron-701SD:~$ td columns
Traceback (most recent call last):
  File "/home/ron/.local/bin/topydo", line 11, in <module>
    sys.exit(main())
  File "/home/ron/.local/lib/python3.4/site-packages/topydo/ui/UILoader.py", line 53, in main
    UIApplication().run()
  File "/home/ron/.local/lib/python3.4/site-packages/topydo/ui/columns/Main.py", line 255, in __init__
    self._screen.register_palette(create_color_palette())
  File "/usr/local/lib/python3.4/dist-packages/urwid/display_common.py", line 742, in register_palette
    self.register_palette_entry(*item)
  File "/usr/local/lib/python3.4/dist-packages/urwid/display_common.py", line 823, in register_palette_entry
    high_88 = AttrSpec(foreground_high, background_high, 88)
  File "/usr/local/lib/python3.4/dist-packages/urwid/display_common.py", line 486, in __init__
    self.background = bg
  File "/usr/local/lib/python3.4/dist-packages/urwid/display_common.py", line 610, in _set_background
    "in background (%s)") % (repr(background),))
urwid.display_common.AttrSpecError: Unrecognised color specification in background ('h239')
```
**Question:**
Did I accidentally loose something during the _terminal_velocity_ uninstall, something that's not being replaced by the _topydo columns_ reinstall?

**Comment by RonCam** [comment]
Columns mode is back in operation, after entering this in terminal:
` ~$ sudo pip3 install urwid --upgrade`
I'll leave this post here as reference to any other users who may encounter a similar problem.  The underlying problem, I think, will be resolved when I upgrade to the most recent _Bodhi Linux_ -- and a newer version of _pip3_.  Until then, the above serves as a 'work-around'.
