### ISSUE TITLE
Return from suspend (ctrl+z) leads to immediate traceback and crash

### ISSUE THREAD

**Issue by suchkultur** [bram85/topydo#218]
### Error description

When i enter `topydo columns`, then suspend it with `ctrl+z` (SIGTSTP i guess) and then to `fg` immediately after it has been suspended, the application crashes with this traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/topydo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/topydo/ui/UILoader.py", line 53, in main
    UIApplication().run()
  File "/usr/local/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 724, in run
    self.mainloop.run()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
KeyError: 0
```

I quickly searched the issue tracker at https://github.com/urwid/urwid/issues, but didn't find an open or closed issue on that. Maybe its just that my use case (proper handling of unix process mgmt. signals) has not been implemented?

I'd be happy to provide more information if needed to narrow this down.

### Environment

* topydo 0.13
* MacOS 10.13.2 (17C205)
* zsh 5.4.2 (x86_64-apple-darwin17.3.0)

**Comment by bram85** [comment]
I cannot reproduce this in my environment, `fg` restores it properly (environment: Cygwin).

Do you get (more or less) the same trace for other applications based on urwid? I know that the `pudb` debugger uses this toolkit as well.

**Comment by mruwek** [comment]
@bram85
> I cannot reproduce this in my environment, fg restores it properly (environment: Cygwin).

I can. I investigated it a bit and it happens if urwid is >=2.0.0. I've also did some bisecting and I'll post an issue with my results on urwids tracker. For the time being we can modify `setup.py` to freeze urwid version at 1.3.1 maximum.
