### ISSUE TITLE
`RuntimeError: dictionary changed size during iteration`

### ISSUE THREAD

**Issue by Ekleog** [bram85/topydo#236]
I think this happened because I tried to “do” two tasks too fast. Basically, I pressed `x` twice, and the first task had not been marked done yet when I pressed it the second time.

That said, I'm unable to reproduce, so I'll just dump the backtrace I have (unfortunately I didn't think of trying to reproduce in another terminal, so it's a bit mangled. I tried to censor only stuff that was personal in nature (my todo items…), hopefully preserving as much the layout as I could

```
raceback (most recent call last):----------------[censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/bin/.topydo-wrapped", line 12, in <module>[censored]
[censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/UILoader.py", line 53, in main[censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 722, in runier[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in runy[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run[censored]
    self._loop()[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 719, in _loop[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/raw_display.py", line 393, in <lambda>[censored]
    event_loop, callback, self.get_available_raw_input()) [censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/raw_display.py", line 493, in parse_input[censored]
    callback(processed, processed_codes)---------[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 403, in _updateset[censored]
    self.process_input(keys)[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 503, in process_input[censored]
    k = self._topmost_widget.keypress(self.screen_size, k)[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/wimp.py", line 643, in keypress[censored]
    return self._current_widget.keypress(size, key)[censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 108, in keypress[censored]
    key = self.focus.keypress(tsize, p_key)[censored]
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/container.py", line 2269, in keypress[censored]
    key = w.keypress((mc,) + size[1:], key) [censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/TodoListWidget.py", line 167, in keypress [censored]
    self.resolve_action(action, p_size)porte-doc [censored]
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/TodoListWidget.py", line 271, in resolve_action  [censored]
Exception in thread Thread-1:  [censored]
Traceback (most recent call last):[censored]
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner[censored]
    self.run()[censored]
  File "/nix/store/clc71ca7ldm8dm5shqxi788mdz2m58y0-python3.6-watchdog-0.8.3/lib/python3.6/site-packages/watchdog/observers/api.py", line 199, in run[censored]
    self.dispatch_events(self.event_queue, self.timeout)
  File "/nix/store/clc71ca7ldm8dm5shqxi788mdz2m58y0-python3.6-watchdog-0.8.3/lib/python3.6/site-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/nix/store/clc71ca7ldm8dm5shqxi788mdz2m58y0-python3.6-watchdog-0.8.3/lib/python3.6/site-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/lib/TodoFileWatched.py", line 69, in on_modified
    self._handle(p_event)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/lib/TodoFileWatched.py", line 59, in _handle
    p_on_update()
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 135, in callback
    self._redraw()
i/columns/Main.py", line 656, in _redraw
    self.mainloop.draw_screen()
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/raw_display.py", line 671, in draw_screen
    assert self._started
AssertionError

    self._execute_on_selected(cmd, execute_signal)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/TodoListWidget.py", line 247, in _execute_on_selected
    urwid.emit_signal(self, p_execute_signal, p_cmd_str, todo_id)
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/nix/store/35yys0636miqjkc8lqyz2lv9alx5vizj-python3.6-urwid-1.3.1/lib/python3.6/site-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 518, in execute_silent
    self._execute_handler(p_cmd, p_todo_id, lambda _: None)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/columns/Main.py", line 346, in _execute_handler
    self._backup(subcommand, p_label=label)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/ui/CLIApplicationBase.py", line 253, in _backup
    self.backup = ChangeSet(self.todolist, p_label=label)
  File "/nix/store/8rcrc1w1q9w1dnwaj6bxpb8pc30lf835-topydo-0.13/lib/python3.6/site-packages/topydo/lib/ChangeSet.py", line 47, in __init__
    self.todolist = deepcopy(p_todolist)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/nix/store/lp7x6ziq5b2zihgad0i8a28xxvz5vnrr-python3-3.6.4/lib/python3.6/copy.py", line 239, in _deepcopy_dict
    for key, value in x.items():
RuntimeError: dictionary changed size during iteration
```

(note I'm running topydo in its state given at https://github.com/bram85/topydo/pull/230, but I can't think of any way these changes could trigger this bug)

**Comment by bram85** [comment]
I guess a race condition that slipped into topydo due to the introduction of the `watchdog` module. Need to investigate.
