### ISSUE TITLE
Revert ls tests broken with arrow==0.15.4

### ISSUE THREAD

**Issue by jonringer** [bram85/topydo#271]
Running the tests suite:
```
======================================================================
ERROR: test_revert_ls (test.test_revert_command.RevertCommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/test/test_revert_command.py", line 310, in test_revert_ls
    command_executer(RevertCommand, ['ls'], self.todolist, None, self.out, self.error, None)
  File "/build/source/test/test_revert_command.py", line 58, in command_executer
    command.execute()
  File "/build/source/topydo/commands/RevertCommand.py", line 51, in execute
    self._handle_args(arg)
  File "/build/source/topydo/commands/RevertCommand.py", line 89, in _handle_args
    self._handle_ls()
  File "/build/source/topydo/commands/RevertCommand.py", line 101, in _handle_ls
    time = arrow.get(timestamp).format('YYYY-MM-DD HH:mm:ss')
  File "/nix/store/9mb40ydqv3kwiqmmdqni8v0a2x2lbxpf-python3.7-arrow-0.15.4/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/nix/store/9mb40ydqv3kwiqmmdqni8v0a2x2lbxpf-python3.7-arrow-0.15.4/lib/python3.7/site-packages/arrow/factory.py", line 193, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/nix/store/9mb40ydqv3kwiqmmdqni8v0a2x2lbxpf-python3.7-arrow-0.15.4/lib/python3.7/site-packages/arrow/parser.py", line 211, in parse_iso
    return self._parse_multiformat(datetime_string, formats)
  File "/nix/store/9mb40ydqv3kwiqmmdqni8v0a2x2lbxpf-python3.7-arrow-0.15.4/lib/python3.7/site-packages/arrow/parser.py", line 483, in _parse_multiformat
    string, ", ".join(formats)
arrow.parser.ParserError: Could not match input '5' to any of the following formats: YYYY-MM-DD, YYYY-M-DD, YYYY-M-D, YYYY/MM/DD, YYYY/M/DD, YYYY/M/D, YYYY.MM.DD, YYYY.M.DD, YYYY.M.D, YYYYMMDD, YYYY-DDDD, YYYYDDDD, YYYY-MM, YYYY/MM, YYYY.MM, YYYY

```

system info:
python==3.6.10
arrow==0.15.4
topydo==0.13

**Comment by jonringer** [comment]
fixed on nixpkgs, closing due to inactivity
