### ISSUE TITLE
Error when HOME environment variable does not exist

### ISSUE THREAD

**Issue by robertvanbregt** [bram85/topydo#31]
The environment on my employer supplied laptop does not set the `HOME` variable. When I run `topydo`, an error is raised:

<pre>
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\topydo.exe\__main__.py", line 5, in <module>
  File "C:\Python27\lib\site-packages\topydo\cli\Main.py", line 89, in <module>
    config()
  File "C:\Python27\lib\site-packages\topydo\lib\Config.py", line 190, in config
    config.instance = _Config(p_path)
  File "C:\Python27\lib\site-packages\topydo\lib\Config.py", line 73, in __init__
    self._home_config_path(),
  File "C:\Python27\lib\site-packages\topydo\lib\Config.py", line 93, in _home_config_path
    return os.path.join(os.getenv('HOME'), '.topydo')
  File "C:\Python27\lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python27\lib\ntpath.py", line 114, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
</pre>

As a temporary workaround I have set

<pre>
SET HOME=%HOMESHARE%
</pre>

 and then `topydo` runs fine.

**Comment by mruwek** [comment]
I believe it's fixed in master with c0e6447.

**Comment by robertvanbregt** [comment]
Could be. I have installed today using `pip install topydo` and that release still had the error. When will a new release be available throuhg pip?

**Comment by bram85** [comment]
I also backported the fix that @mruwek mentioned to the `stable` branch (https://github.com/bram85/topydo/commit/daf26fa01e162989ceb6c380ef30a8676f78e7c6). I'll probably make a 0.3.2 somewhere later this week with this fix.

**Comment by mruwek** [comment]
@robertvanbregt 
You can also always download ZIP of `master` or `stable` branch, unpack it and install with: `pip install . --upgrade`

**Comment by robertvanbregt** [comment]
I will wait for the pypi release of 0.3.2

**Comment by bram85** [comment]
Just released 0.3.2, you can download it from pip now.

**Comment by robertvanbregt** [comment]
I installed 0.3.2 and it is fixed. However, I might have found a new issue: #37.
