### ISSUE TITLE
Using "keep_sorted" gives "RuntimeError: maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by vixsomnis** [bram85/topydo#46]
Turning off the setting for sorting the file restored functionality, so
I believe the problem is the 'keep_sorted' setting.

## Inputted command:

    [ vixsomnis: Code/notestxt ]
        > % topydo add "(B) Figure out efficient note abstraction and parsing"
            2> stderr.log > stdout.log

## stdout:

    |  2| (B) 2015-06-06 Figure out efficient note abstraction and parsing

## stderr:

    Traceback (most recent call last):
    File "/usr/bin/topydo", line 9, in <module>
        load_entry_point('topydo==0.4', 'console_scripts', 'topydo')()
    File "/usr/lib/python2.7/site-packages/topydo/cli/UILoader.py", line 42, in main
        CLIApplication().run()
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLI.py", line 56, in run
        if self._execute(subcommand, args) == False:
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 197, in _execute
        self._post_execute()
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 207, in _post_execute
        self._execute(SortCommand, [])
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 197, in _execute
        self._post_execute()
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 207, in _post_execute

    {{ ........... ~1995 times }}

    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 197, in _execute
        self._post_execute()
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 204, in _post_execute
        self._archive()
    File "/usr/lib/python2.7/site-packages/topydo/cli/CLIApplicationBase.py", line 163, in _archive
        archive = TodoListBase.TodoListBase(archive_file.read())
    File "/usr/lib/python2.7/site-packages/topydo/lib/TodoFile.py", line 36, in read
        todofile = codecs.open(self.path, 'r', encoding="utf-8")
    File "/usr/lib/python2.7/codecs.py", line 888, in open
        srw = StreamReaderWriter(file, info.streamreader, info.streamwriter, errors)
    File "/usr/lib/python2.7/codecs.py", line 668, in __init__
        self.reader = Reader(stream, errors)
    RuntimeError: maximum recursion depth exceeded while calling a Python object

## topydo.conf diff with default

    0a1,2
    > ; See https://github.com/bram85/topydo/wiki/Configuration for more info
    >
    3,4c5,6
    < filename                    = TODO
    < archive_filename            = DONE
    ---
    > ; filename                  = todo.txt
    > ; archive_filename          = done.txt
    20c22
    < keep_sorted                 = 1
    ---
    > keep_sorted                 = 0

**Comment by bram85** [comment]
Thanks for the detailed bug report, I see what's going on. I'll try to come up with a fix and make a new release.
