### ISSUE TITLE
failure on master (commit d9c9fdc)

### ISSUE THREAD

**Issue by c-cube** [bram85/topydo#6]
on a task `'(A) 2015-01-13 foobar @home rec:1 year'` (number 6):

```
$ topydo do 6
Traceback (most recent call last):
  File "/home/simon/bin/topydo", line 9, in <module>
    load_entry_point('topydo==0.1.1', 'console_scripts', 'topydo')()
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/cli/Main.py", line 286, in main
    CLIApplication().run()
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/cli/Main.py", line 273, in run
    if self._execute(subcommand, args) == False:
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/cli/Main.py", line 213, in _execute
    return False if command.execute() == False else True
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/lib/DCommand.py", line 145, in execute
    self.execute_specific()
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/lib/DoCommand.py", line 78, in execute_specific
    self._handle_recurrence()
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/lib/DoCommand.py", line 56, in _handle_recurrence
    self.completion_date)
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/lib/Recurrence.py", line 58, in advance_recurring_todo
    return _advance_recurring_todo_helper(p_todo, p_offset)
  File "/home/simon/.local/lib/python2.7/site-packages/topydo/lib/Recurrence.py", line 47, in _advance_recurring_todo_helper
    todo.set_tag(config().tag_due(), new_due.isoformat())
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

**Comment by mruwek** [comment]
@c-cube:

Recurrence tag is wrongly formatted.

Take a look at [Wiki ](https://github.com/bram85/topydo/wiki/Recurrence):
> The tag value's format is as follows: a number suffixed by d, w, m or y (days, weeks, months, years respectively). 

So your example task shall look like: `'(A) 2015-01-13 foobar @home rec:1y'`

**Comment by bram85** [comment]
Nevertheless, this should be handled without spitting stack traces.

**Comment by c-cube** [comment]
Oh, thanks, my apologies. It would be nice to have better errors though, I agree.
